const C=window.AUTOFLOW_CONFIG||{},JAVA=C.JAVA_API_URL||"http://localhost:8080",PY=C.PYTHON_API_URL||"http://localhost:8001";
let execs=[],liveCustomers=[],activityChart=null,impactChart=null;
const fallbackCustomers=[{name:"Maya Khan",email:"maya@northstar.io",company:"Northstar Labs",status:"Active",created:"Today"},{name:"Daniel Reed",email:"daniel@vertex.co",company:"Vertex Systems",status:"Active",created:"Yesterday"},{name:"Aisha Malik",email:"aisha@nova.pk",company:"Nova Digital",status:"Lead",created:"Sep 29"},{name:"Omar Farooq",email:"omar@lumina.ai",company:"Lumina AI",status:"Active",created:"Sep 27"}];
const flows=[["Customer onboarding","Webhook → SQL → Email → Task",["Webhook","SQL","Email","Task"]],["Lead qualification","Webhook → Score → Decision → Response",["Webhook","Score","Decision","Response"]],["Daily operations report","Schedule → SQL → Python → Email",["Schedule","SQL","Python","Email"]],["Overdue task monitor","Schedule → SQL → Alert",["Schedule","SQL","Filter","Alert"]],["CSV customer import","Upload → Python → Clean → SQL",["Upload","Python","Clean","SQL"]],["Payment event handler","Webhook → Java → SQL → n8n",["Webhook","Java","SQL","n8n"]]];
const toast=m=>{const e=document.querySelector("#toast");if(!e)return;e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)};
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));const t=document.querySelector("#title");if(t)t.textContent={dashboard:"Command Center",customers:"Customers",automations:"Automations",executions:"Execution History",reports:"Reports"}[id]||"AutoFlow";document.querySelector("#sidebar")?.classList.remove("open")}
document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>page(x.dataset.page));document.querySelectorAll("[data-jump]").forEach(x=>x.onclick=()=>page(x.dataset.jump));
document.querySelector("#menu")?.addEventListener("click",()=>document.querySelector("#sidebar")?.classList.toggle("open"));document.querySelector("#theme")?.addEventListener("click",()=>document.body.classList.toggle("light"));
function renderServices(javaOk=false,pythonOk=false,n8nMain=false,n8nLead=false){const el=document.querySelector("#services");if(!el)return;const rows=[["J","Spring Boot API","Java core service",javaOk],["Py","FastAPI Worker","Python automation",pythonOk],["n8n","n8n Orchestrator",n8nMain?"Customer webhook configured":"Webhook needs production URL",n8nMain],["LQ","Lead Workflow",n8nLead?"Lead webhook configured":"Optional second workflow",n8nLead]];el.innerHTML=rows.map(s=>'<div class="service"><span class="service-icon">'+s[0]+'</span><div><b>'+s[1]+'</b><small>'+s[2]+'</small></div><small>'+(s[3]?"Live":"Setup")+'</small><i style="background:'+(s[3]?"var(--green)":"var(--red)")+'"></i></div>').join("")}
const topFlows=document.querySelector("#topFlows");if(topFlows)topFlows.innerHTML=flows.slice(0,4).map(f=>'<div class="flow-row"><span class="flow-icon">⌁</span><div><b>'+f[0]+'</b><small>'+f[1]+'</small></div><span class="pill">Active</span></div>').join("");
function formatStarted(v){if(!v)return"—";const d=new Date(v);if(Number.isNaN(d.getTime()))return v;const s=Math.floor((Date.now()-d.getTime())/1000);if(s<60)return"Just now";const m=Math.floor(s/60);if(m<60)return m+" min ago";const h=Math.floor(m/60);if(h<24)return h+" hr"+(h===1?"":"s")+" ago";const days=Math.floor(h/24);return days+" day"+(days===1?"":"s")+" ago"}
function renderExec(a=execs){const feed=document.querySelector("#feed"),table=document.querySelector("#execBody");if(!a.length){if(feed)feed.innerHTML='<div class="run"><span class="run-icon">⌁</span><div><b>No executions yet</b><small>Run an automation to create one.</small></div></div>';if(table)table.innerHTML='<tr><td colspan="5" style="text-align:center;padding:30px;">No executions found.</td></tr>';return}if(feed)feed.innerHTML=a.slice(0,4).map(x=>'<div class="run"><span class="run-icon '+(x.status==="failed"?"fail":"")+'">'+(x.status==="failed"?"!":"✓")+'</span><div><b>'+(x.workflow||"Unknown workflow")+'</b><small>'+(x.id||"—")+' · '+(x.duration||"—")+'</small></div><time>'+formatStarted(x.started)+'</time></div>').join("");if(table)table.innerHTML=a.map(x=>'<tr><td><b>'+(x.id||"—")+'</b></td><td>'+(x.workflow||"—")+'</td><td><span class="pill '+(x.status==="failed"?"failed":"")+'">'+(x.status||"unknown")+'</span></td><td>'+(x.duration||"—")+'</td><td>'+formatStarted(x.started)+'</td></tr>').join("")}
async function getExec(show=false){try{const r=await fetch(JAVA+"/api/executions");if(!r.ok)throw new Error("HTTP "+r.status);execs=await r.json();renderExec(execs);if(show)toast("Execution history refreshed.")}catch(e){console.error(e);execs=[];renderExec([]);if(show)toast("Could not load execution history.")}}
document.querySelector("#refresh")?.addEventListener("click",async()=>{await Promise.all([getExec(true),loadDashboardStats(),loadDashboardAnalytics(),checkServiceHealth()])});document.querySelector("#refreshTable")?.addEventListener("click",async()=>{await getExec(true);await loadDashboardStats();await loadDashboardAnalytics()});
function renderCustomers(a){const body=document.querySelector("#customersBody");if(!body)return;if(!a.length){body.innerHTML='<tr><td colspan="5" style="text-align:center;padding:30px;">No customers found.</td></tr>';return}body.innerHTML=a.map(c=>'<tr><td><b>'+(c.name||"—")+'</b><small>'+(c.email||"—")+'</small></td><td>'+(c.company||"—")+'</td><td><span class="pill">'+(c.status||"Active")+'</span></td><td>'+formatStarted(c.createdAt||c.created)+'</td><td>•••</td></tr>').join("")}
async function loadCustomers(){try{const r=await fetch(JAVA+"/api/customers");if(!r.ok)throw new Error("HTTP "+r.status);liveCustomers=await r.json();renderCustomers(liveCustomers)}catch(e){console.error(e);liveCustomers=fallbackCustomers;renderCustomers(liveCustomers)}}
document.querySelector("#searchCustomer")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase();renderCustomers(liveCustomers.filter(c=>((c.name||"")+" "+(c.email||"")+" "+(c.company||"")).toLowerCase().includes(q)))});
const flowCards=document.querySelector("#flowCards");if(flowCards)flowCards.innerHTML=flows.map(f=>'<article><span class="flow-icon">⌁</span><h3>'+f[0]+'</h3><p>'+f[1]+'</p><div class="flowline">'+f[2].map((x,i)=>'<span>'+x+'</span>'+(i<f[2].length-1?"→":"")).join("")+'</div><div class="auto-meta"><span>API tracked</span><span>n8n</span></div><button class="ghost runFlow" data-name="'+f[0]+'">▶ Run now</button></article>').join("");
async function trigger(name){try{const payload=name==="Lead qualification"?{source:"autoflow-dashboard",email:"lead@example.com",company:"Demo Company",intent:"high"}:{source:"autoflow-dashboard"};const r=await fetch(JAVA+"/api/automations/trigger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event:"manual_trigger",workflow:name,payload})});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.message||("HTTP "+r.status));toast(name+" completed.");await Promise.all([getExec(),loadDashboardStats(),loadDashboardAnalytics()])}catch(e){console.error(e);toast("Automation failed: "+(e.message||"Unknown error"))}}
document.querySelectorAll(".runFlow").forEach(x=>x.onclick=()=>trigger(x.dataset.name));document.querySelector("#demoTrigger")?.addEventListener("click",()=>trigger("Customer onboarding"));
const fm=document.querySelector("#flowModal"),cm=document.querySelector("#customerModal");document.querySelector("#newFlow")?.addEventListener("click",()=>fm?.classList.add("show"));document.querySelectorAll(".x").forEach(x=>x.onclick=()=>fm?.classList.remove("show"));document.querySelector("#saveFlow")?.addEventListener("click",()=>{fm?.classList.remove("show");toast("Workflow draft created.")});document.querySelector("#addCustomer")?.addEventListener("click",()=>cm?.classList.add("show"));document.querySelectorAll(".cx").forEach(x=>x.onclick=()=>cm?.classList.remove("show"));
document.querySelector("#saveCustomer")?.addEventListener("click",async()=>{const name=document.querySelector("#cName")?.value.trim(),email=document.querySelector("#cEmail")?.value.trim(),company=document.querySelector("#cCompany")?.value.trim();if(!name||!email){toast("Name and email are required.");return}try{const r=await fetch(JAVA+"/api/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,company,status:"Active"})});if(!r.ok)throw new Error(await r.text());toast("Customer saved to PostgreSQL.");cm?.classList.remove("show");await Promise.all([loadCustomers(),loadDashboardStats()])}catch(e){console.error(e);toast("Could not save customer.")}});
const pal=document.querySelector("#palette"),pi=document.querySelector("#paletteInput");function palette(v=true){if(!pal)return;pal.classList.toggle("show",v);if(v&&pi)setTimeout(()=>pi.focus(),20)}document.querySelector("#cmd")?.addEventListener("click",()=>palette());document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();palette()}if(e.key==="Escape")palette(false)});document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>{page(x.dataset.go);palette(false)});
document.querySelector("#reportBtn")?.addEventListener("click",async()=>{try{const r=await fetch(PY+"/reports/daily",{method:"POST"});if(!r.ok)throw new Error("HTTP "+r.status);toast("Python service generated the daily report.")}catch(e){console.error(e);toast("Could not generate report.")}});
async function loadDashboardStats(){try{const r=await fetch(JAVA+"/api/dashboard/stats");if(!r.ok)throw new Error("HTTP "+r.status);const d=await r.json();const set=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=v};set("#metricRuns",Number(d.totalRuns||0).toLocaleString());set("#metricSuccess",(d.successRate||0)+"%");set("#metricCustomers",Number(d.customers||0).toLocaleString());set("#metricDuration",(d.averageDurationMs||0)+"ms");set("#heroSuccess",d.successRate||0);set("#reportHealth",(d.successRate||0)+"%");set("#metricRunsChange",(d.failedRuns||0)+" failed");set("#metricSuccessText",(d.successRuns||0)+" successful");set("#metricCustomersText","Database connected");set("#metricDurationText","Average response")}catch(e){console.error("Dashboard stats error:",e)}}
async function loadDashboardAnalytics(){try{const r=await fetch(JAVA+"/api/dashboard/analytics");if(!r.ok)throw new Error("HTTP "+r.status);const d=await r.json();if(activityChart){activityChart.data.labels=d.labels||[];activityChart.data.datasets[0].data=d.activity||[];activityChart.update()}if(impactChart){const rows=d.workflowImpact||[];impactChart.data.labels=rows.map(x=>x.workflow);impactChart.data.datasets[0].data=rows.map(x=>x.runs);impactChart.update()}}catch(e){console.error("Dashboard analytics error:",e)}}
async function checkServiceHealth(){let javaOk=false,pythonOk=false,n8nMain=false,n8nLead=false;try{javaOk=(await fetch(JAVA+"/api/health")).ok}catch{}try{pythonOk=(await fetch(PY+"/health")).ok}catch{}try{const r=await fetch(JAVA+"/api/automations/status");if(r.ok){const d=await r.json();n8nMain=!!d.customerOnboardingConfigured;n8nLead=!!d.leadQualificationConfigured}}catch{}renderServices(javaOk,pythonOk,n8nMain,n8nLead)}
if(window.Chart){Chart.defaults.color="#8c96ad";Chart.defaults.borderColor="rgba(255,255,255,.05)";const activity=document.querySelector("#activity"),impact=document.querySelector("#impact");if(activity)activityChart=new Chart(activity,{type:"line",data:{labels:[],datasets:[{data:[],tension:.4,fill:true,backgroundColor:"rgba(124,92,255,.08)",borderColor:"#8d73ff",pointRadius:2,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,ticks:{precision:0}}}}});if(impact)impactChart=new Chart(impact,{type:"bar",data:{labels:[],datasets:[{data:[],backgroundColor:["#8061ff","#20d6c7","#ffad67","#48db91","#68c9ff"],borderRadius:7}]},options:{plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,ticks:{precision:0}}}}})}
Promise.all([getExec(),loadCustomers(),loadDashboardStats(),loadDashboardAnalytics(),checkServiceHealth()]);
