const C=window.AUTOFLOW_CONFIG||{},JAVA=C.JAVA_API_URL||"http://localhost:8080",PY=C.PYTHON_API_URL||"http://localhost:8001";
const execs=[{id:"RUN-2491",workflow:"Customer onboarding",status:"success",duration:"1.84s",started:"2 min ago"},{id:"RUN-2490",workflow:"Lead qualification",status:"success",duration:"980ms",started:"8 min ago"},{id:"RUN-2489",workflow:"Daily operations report",status:"success",duration:"2.31s",started:"17 min ago"},{id:"RUN-2488",workflow:"Invoice follow-up",status:"failed",duration:"714ms",started:"24 min ago"}];
const customers=[{name:"Maya Khan",email:"maya@northstar.io",company:"Northstar Labs",status:"Active",created:"Today"},{name:"Daniel Reed",email:"daniel@vertex.co",company:"Vertex Systems",status:"Active",created:"Yesterday"},{name:"Aisha Malik",email:"aisha@nova.pk",company:"Nova Digital",status:"Lead",created:"Sep 29"},{name:"Omar Farooq",email:"omar@lumina.ai",company:"Lumina AI",status:"Active",created:"Sep 27"}];
const flows=[["Customer onboarding","Webhook → SQL → Email → Task",412,["Webhook","SQL","Email","Task"]],["Lead qualification","Form → Score → CRM → Notify",286,["Form","Score","CRM","Notify"]],["Daily operations report","Schedule → SQL → Python → Email",124,["Schedule","SQL","Python","Email"]],["Overdue task monitor","Schedule → SQL → Alert",98,["Schedule","SQL","Filter","Alert"]],["CSV customer import","Upload → Python → Clean → SQL",54,["Upload","Python","Clean","SQL"]],["Payment event handler","Webhook → Java → SQL → n8n",77,["Webhook","Java","SQL","n8n"]]];
const toast=m=>{let e=document.querySelector("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)};
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));document.querySelector("#title").textContent={dashboard:"Command Center",customers:"Customers",automations:"Automations",executions:"Execution History",reports:"Reports"}[id];document.querySelector("#sidebar").classList.remove("open")}
document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>page(x.dataset.page));document.querySelectorAll("[data-jump]").forEach(x=>x.onclick=()=>page(x.dataset.jump));document.querySelector("#menu").onclick=()=>document.querySelector("#sidebar").classList.toggle("open");document.querySelector("#theme").onclick=()=>document.body.classList.toggle("light");
document.querySelector("#services").innerHTML=[["J","Spring Boot API","Java core service","84 ms"],["Py","FastAPI Worker","Python automation","61 ms"],["n8n","n8n Orchestrator","Webhook engine","109 ms"],["SQL","PostgreSQL","Primary database","23 ms"]].map(s=>'<div class="service"><span class="service-icon">'+s[0]+'</span><div><b>'+s[1]+'</b><small>'+s[2]+'</small></div><small>'+s[3]+'</small><i></i></div>').join("");
document.querySelector("#topFlows").innerHTML=flows.slice(0,4).map(f=>'<div class="flow-row"><span class="flow-icon">⌁</span><div><b>'+f[0]+'</b><small>'+f[1]+'</small></div><span class="pill">Active</span><em>'+f[2]+' runs</em></div>').join("");
function renderExec(a=execs){document.querySelector("#feed").innerHTML=a.slice(0,4).map(x=>'<div class="run"><span class="run-icon '+(x.status==="failed"?"fail":"")+'">'+(x.status==="failed"?"!":"✓")+'</span><div><b>'+x.workflow+'</b><small>'+x.id+' · '+x.duration+'</small></div><time>'+x.started+'</time></div>').join("");document.querySelector("#execBody").innerHTML=a.map(x=>'<tr><td><b>'+x.id+'</b></td><td>'+x.workflow+'</td><td><span class="pill">'+x.status+'</span></td><td>'+x.duration+'</td><td>'+x.started+'</td></tr>').join("")}renderExec();
async function getExec(){try{let r=await fetch(JAVA+"/api/executions");if(!r.ok)throw 0;renderExec(await r.json())}catch{renderExec();toast("Demo data shown — connect the Java API for live execution history.")}}document.querySelector("#refresh").onclick=getExec;document.querySelector("#refreshTable").onclick=getExec;
function renderCustomers(a=customers){document.querySelector("#customersBody").innerHTML=a.map(c=>'<tr><td><b>'+c.name+'</b><small>'+c.email+'</small></td><td>'+c.company+'</td><td><span class="pill">'+c.status+'</span></td><td>'+(c.created||"—")+'</td><td>•••</td></tr>').join("")}renderCustomers();
fetch(JAVA+"/api/customers").then(r=>r.ok?r.json():Promise.reject()).then(d=>d.length&&renderCustomers(d)).catch(()=>{});
document.querySelector("#searchCustomer").oninput=e=>renderCustomers(customers.filter(c=>(c.name+c.email+c.company).toLowerCase().includes(e.target.value.toLowerCase())));
document.querySelector("#flowCards").innerHTML=flows.map(f=>'<article><span class="flow-icon">⌁</span><h3>'+f[0]+'</h3><p>'+f[1]+'</p><div class="flowline">'+f[3].map((x,i)=>'<span>'+x+'</span>'+(i<f[3].length-1?"→":"")).join("")+'</div><div class="auto-meta"><span>'+f[2]+' runs</span><span>99.4% success</span></div><button class="ghost runFlow" data-name="'+f[0]+'">▶ Run now</button></article>').join("");
async function trigger(name){try{let r=await fetch(JAVA+"/api/automations/trigger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event:"manual_trigger",workflow:name,payload:{source:"autoflow-dashboard"}})});if(!r.ok)throw 0;toast(name+" sent to n8n.")}catch{toast("Set N8N_WEBHOOK_URL in Render to trigger live n8n workflows.")}}document.querySelectorAll(".runFlow").forEach(x=>x.onclick=()=>trigger(x.dataset.name));document.querySelector("#demoTrigger").onclick=()=>trigger("Customer onboarding");
const fm=document.querySelector("#flowModal");document.querySelector("#newFlow").onclick=()=>fm.classList.add("show");document.querySelectorAll(".x").forEach(x=>x.onclick=()=>fm.classList.remove("show"));document.querySelector("#saveFlow").onclick=()=>{fm.classList.remove("show");toast("Workflow draft created. Connect it to n8n to activate.")};
const cm=document.querySelector("#customerModal");document.querySelector("#addCustomer").onclick=()=>cm.classList.add("show");document.querySelectorAll(".cx").forEach(x=>x.onclick=()=>cm.classList.remove("show"));document.querySelector("#saveCustomer").onclick=async()=>{let b={name:cName.value,email:cEmail.value,company:cCompany.value,status:"Active"};try{let r=await fetch(JAVA+"/api/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});if(!r.ok)throw 0;toast("Customer saved to PostgreSQL.")}catch{customers.unshift({...b,created:"Now"});renderCustomers();toast("Demo mode: customer added locally.")}cm.classList.remove("show")};
const pal=document.querySelector("#palette"),pi=document.querySelector("#paletteInput");function palette(v=true){pal.classList.toggle("show",v);if(v)setTimeout(()=>pi.focus(),20)}document.querySelector("#cmd").onclick=()=>palette();document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();palette()}if(e.key==="Escape")palette(false)});document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>{page(x.dataset.go);palette(false)});
document.querySelector("#reportBtn").onclick=async()=>{try{let r=await fetch(PY+"/reports/daily",{method:"POST"});if(!r.ok)throw 0;toast("Python service generated the daily report.")}catch{toast("Demo report generated — connect FastAPI for live processing.")}};
if(window.Chart){Chart.defaults.color="#8c96ad";Chart.defaults.borderColor="rgba(255,255,255,.05)";new Chart(activity,{type:"line",data:{labels:["Thu","Fri","Sat","Sun","Mon","Tue","Wed"],datasets:[{data:[132,160,151,182,208,221,248],tension:.4,fill:true,backgroundColor:"rgba(124,92,255,.08)",borderColor:"#8d73ff",pointRadius:0,borderWidth:2},{data:[5,3,7,4,6,2,3],tension:.4,borderColor:"#ff7384",pointRadius:0,borderWidth:1}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true}}}});new Chart(impact,{type:"bar",data:{labels:["Onboarding","Leads","Reports","Tasks","CSV"],datasets:[{data:[94,71,53,66,44],backgroundColor:["#8061ff","#20d6c7","#ffad67","#48db91","#68c9ff"],borderRadius:7}]},options:{plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true}}}})}